import {Outfit} from 'next/font/google';
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import Provider from './Provider.js'

const outfit = Outfit({
  subsets:['latin'],
  weight:['300']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={outfit.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}