import {Outfit} from 'next/font/google';
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import Provider from './Provider.js'
import { ThemeProvider } from './_context/ThemeContext';

const outfit = Outfit({
  subsets:['latin'],
  weight:['300']
});

export const metadata = {
  title: "AI-LMS",
  description: "Generated by create next app",
  icons: {
    icon: '/logoo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={outfit.className}>
        <Provider>
          <ThemeProvider>
                {children}
          </ThemeProvider>
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}


